language: ruby

rvm:
  # start with the latest
  - 2.4.3
  - jruby-9.1.15.0

  # older versions
  - 2.3.4
  - 2.2.7
  - 2.1.9
  - 2.0.0
  - 1.9.3

  - jruby-9.0.5.0
  - jruby-1.7.27

  - ruby-head
  - jruby-head

  - rbx-3

jdk:
  - oraclejdk8

sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - rvm: 2.3.4
      jdk: oraclejdk8
      env: COVERAGE=1
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 1.9.3
    - rvm: rbx-3

env:
  global:
    - JAVA_OPTS=-Xmx1024m

before_install:
  - "echo JAVA_OPTS: $JAVA_OPTS"

script: RUBYOPT=-w bundle exec rake ci
