language: ruby

rvm:
  # start with the latest
  - 2.4.0
  - jruby-9.1.5.0

  # older versions
  - 2.3.3
  - 2.2.6
  - 2.1.9
  - 2.0.0
  - 1.9.3

  - jruby-9.0.5.0
  - jruby-1.7.26

  - ruby-head
  - jruby-head

  - rbx

jdk:
  - oraclejdk8

sudo: false

branches:
  only:
    - master

matrix:
  include:
    - rvm: 2.3.1
      jdk: oraclejdk8
      env: COVERAGE=1
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 1.9.3
    - rvm: rbx

env:
  global:
    - JAVA_OPTS=-Xmx1024m

before_install:
  - "echo JAVA_OPTS: $JAVA_OPTS"

script: RUBYOPT=-w bundle exec rake ci
