language: ruby

rvm:
  # start with the latest
  - 2.5.1
  - jruby-9.2.0.0

  # older versions
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 2.0.0

  - jruby-9.1.17.0
  - jruby-9.0.5.0

  - ruby-head
  - ruby-2.6.0-preview2
  - jruby-head

  - rbx-3

jdk:
  - oraclejdk8

sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - rvm: 2.3.7
      jdk: oraclejdk8
      env: COVERAGE=1
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
    - rvm: ruby-2.6.0-preview2

env:
  global:
    - JAVA_OPTS=-Xmx1024m
    - RUBYOPT=-w

before_install:
  - "echo JAVA_OPTS: $JAVA_OPTS"

script: bundle exec rake ci
